'use client';
import { useEffect, useRef, useState } from 'react';
import { ArrowUpRight, Check, ChevronRight, Clock3, Flag, HelpCircle, LockKeyhole, RotateCcw, Shield, Terminal, X, Volume2, VolumeX, Trophy, Crosshair } from 'lucide-react';
import World, { type CameraMode } from './World';
import { challenges, freshProgress, isUnlocked, restoreProgress, runCommand, score, type Challenge, type Progress } from '../../lib/challenges';

const SAVE = 'cipher-vault-v1';
const duration = (s: number) => `${Math.floor(s / 60).toString().padStart(2, '0')}:${(s % 60).toString().padStart(2, '0')}`;
export default function Game() {
  const [progress, setProgress] = useState<Progress>(freshProgress); const [ready, setReady] = useState(false);
  const [started, setStarted] = useState(false); const [near, setNear] = useState<string | null>(null);
  const [active, setActive] = useState<Challenge | null>(null); const [destination, setDestination] = useState<[number, number] | null>(null);
  const [help, setHelp] = useState(false); const [reset, setReset] = useState(false); const [muted, setMuted] = useState(true);
  const [error, setError] = useState(false); const [saved, setSaved] = useState(true); const [toast, setToast] = useState('');
  const [cameraMode, setCameraMode] = useState<CameraMode>('overhead');
  const movement = useRef(new Set<string>()); const audio = useRef<AudioContext | null>(null);
  useEffect(() => { try { const p = restoreProgress(localStorage.getItem(SAVE)); setProgress(p); if (localStorage.getItem('cipher-vault-camera') === 'third-person') setCameraMode('third-person'); } catch { setSaved(false); } setReady(true); return () => { audio.current?.close(); }; }, []);
  useEffect(() => { if (!ready) return; try { localStorage.setItem(SAVE, JSON.stringify(progress)); } catch { setSaved(false); } }, [progress, ready]);
  useEffect(() => { if (!started || help || reset || progress.extracted) return; const t = setInterval(() => { if (!document.hidden) setProgress(p => ({ ...p, seconds: p.seconds + 1 })); }, 1000); return () => clearInterval(t); }, [started, help, reset, progress.extracted]);
  useEffect(() => { if (!toast) return; const t = setTimeout(() => setToast(''), 4500); return () => clearTimeout(t); }, [toast]);
  useEffect(() => { const key = (e: KeyboardEvent) => { if (e.key === 'Escape') { setActive(null); setHelp(false); setReset(false); movement.current.clear(); } }; window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key); }, []);
  useEffect(() => { if (!ready) return; try { localStorage.setItem('cipher-vault-camera', cameraMode); } catch { /* Camera preference is optional. */ } }, [cameraMode, ready]);
  useEffect(() => { const key = (e: KeyboardEvent) => { if (e.repeat || !started || active || help || reset || progress.extracted || (e.target as HTMLElement)?.matches('input,textarea')) return; if (e.key.toLowerCase() === 'v') { e.preventDefault(); setCameraMode(mode => mode === 'overhead' ? 'third-person' : 'overhead'); } }; window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key); }, [started, active, help, reset, progress.extracted]);
  const ping = () => { if (muted) return; try { audio.current ||= new AudioContext(); void audio.current.resume(); const o = audio.current.createOscillator(); const g = audio.current.createGain(); o.connect(g); g.connect(audio.current.destination); o.frequency.setValueAtTime(660, audio.current.currentTime); o.frequency.exponentialRampToValueAtTime(1100, audio.current.currentTime + .15); g.gain.setValueAtTime(.06, audio.current.currentTime); g.gain.exponentialRampToValueAtTime(.001, audio.current.currentTime + .3); o.start(); o.stop(audio.current.currentTime + .3); } catch { /* Audio is optional. */ } };
  const interact = (id: string) => {
    if (id === 'exit') { if (progress.solved.length === challenges.length) { setProgress(p => ({ ...p, extracted: true })); ping(); } else setToast('Extraction locked. Capture all five flags first.'); return; }
    const c = challenges.find(c => c.id === id); if (!c) return;
    if (!isUnlocked(c, progress.solved)) { setToast(`Requires: ${c.requires.map(id => challenges.find(c => c.id === id)?.title).join(' + ')}`); return; }
    movement.current.clear(); setActive(c);
  };
  const capture = (c: Challenge, answer: string) => {
    if (answer.trim() !== c.answer) return 'Flag not recognized. Check the evidence and exact CTF{...} format.';
    if (progress.solved.includes(c.id)) return 'This flag is already captured.';
    setProgress(p => ({ ...p, solved: [...new Set([...p.solved, c.id])] })); ping(); setToast(`${c.title}: flag captured. New access granted.`); return 'FLAG CAPTURED. Read the debrief to understand the defense.';
  };
  const next = challenges.find(c => !progress.solved.includes(c.id) && isUnlocked(c, progress.solved));
  const nearby = challenges.find(c => c.id === near);
  return <main className="game-shell">
    <header className="topbar"><a className="brand" href="./" aria-label="Cipher Vault home"><span className="brand-mark"><Shield size={22}/></span><span>CIPHER<span className="brand-light">VAULT</span><small>CYBERSECURITY TRAINING GROUNDS</small></span></a><div className="operation"><span className="live-dot"/> OPERATION 001 <span className="divider">/</span> THE SILENT BREACH</div><div className="top-actions"><a className="icon-button" href="https://nahmad0.github.io/" title="My websites" aria-label="My websites"><ArrowUpRight size={18}/></a><span className="prototype">PROTOTYPE v0.1</span><button className="icon-button" title={muted ? 'Enable capture sounds' : 'Mute sounds'} aria-label={muted ? 'Enable capture sounds' : 'Mute sounds'} onClick={() => setMuted(v => !v)}>{muted ? <VolumeX size={18}/> : <Volume2 size={18}/>}</button><button className="icon-button" aria-label="Controls and help" onClick={() => setHelp(true)}><HelpCircle size={19}/></button></div></header>
    <div className="play-layout"><section className="arena">
      <World cameraMode={cameraMode} solved={progress.solved} paused={!started || !!active || help || reset || progress.extracted} destination={destination} onNear={setNear} onInteract={interact} onError={() => setError(true)} movement={movement}/>
      <div className="arena-top"><div><span className="eyebrow">SECTOR 01 / TRAINING FACILITY</span><h1>The silent breach<span>.</span></h1><p>Find the evidence. Capture the flags. Secure the vault.</p></div><span className="difficulty"><span/> BEGINNER</span></div>
            <div className="camera-controls" role="group" aria-label="Camera view">
        <div className="camera-options">{(['overhead', 'third-person'] as const).map(mode => <button key={mode} aria-pressed={cameraMode === mode} onClick={() => { movement.current.clear(); setCameraMode(mode); }}>{mode === 'overhead' ? 'Overhead view' : 'Third-person view'}</button>)}<kbd>V</kbd></div>
        {cameraMode === 'third-person' && <div className="camera-orbit"><span>ROTATE</span>{[['↶', 'q'], ['↷', 'r']].map(([label, key]) => <button key={key} aria-label={key === 'q' ? 'Rotate camera left' : 'Rotate camera right'} onPointerDown={e => { e.currentTarget.setPointerCapture(e.pointerId); movement.current.add(key); }} onPointerUp={() => movement.current.delete(key)} onPointerCancel={() => movement.current.delete(key)} onKeyDown={e => { if (e.key === ' ' || e.key === 'Enter') { e.preventDefault(); movement.current.add(key); } }} onKeyUp={() => movement.current.delete(key)} onBlur={() => movement.current.delete(key)}>{label}</button>)}<span>Q / R · RIGHT-DRAG</span></div>}
      </div>
      <div className="scene-tag"><span className="live-dot"/> SIMULATION ONLINE <span className="scene-tag-muted">// ISOLATED LAB</span></div>
      {started && !active && near && <button className="interact" onClick={() => interact(near)}><kbd>E</kbd><span>{near === 'exit' ? 'Enter extraction zone' : `Access ${nearby?.title}`}</span><ChevronRight size={18}/></button>}
      <div className="arena-bottom"><div className="movement-guide"><span><kbd>W</kbd><kbd>A</kbd><kbd>S</kbd><kbd>D</kbd> MOVE</span><span><kbd>E</kbd> INTERACT</span><span><kbd>SPACE</kbd> JUMP</span><span className="desktop">CLICK FLOOR TO WALK</span></div><span className="player-label"><span/> TRAINEE–07</span></div>
      <div className="touch-controls" aria-label="Movement controls">{[['↑','w'],['←','a'],['↓','s'],['→','d'],['⤒',' ']].map(([label, key]) => <button key={key} aria-label={key === ' ' ? 'Jump' : 'Move ' + label} onPointerDown={e => { e.currentTarget.setPointerCapture(e.pointerId); movement.current.add(key); }} onPointerUp={() => movement.current.delete(key)} onPointerCancel={() => movement.current.delete(key)}>{label}</button>)}</div>
    </section>
    <aside className="mission-panel"><div className="panel-header"><span className="eyebrow">MISSION CONTROL</span><span className="live-dot"/></div><h2>Restore the perimeter</h2><p className="panel-intro">Five vulnerabilities. One way out.<br/>Your investigation starts here.</p>
      <div className="stats"><div><Flag size={15}/><strong>{progress.solved.length}<span>/05</span></strong><small>FLAGS CAPTURED</small></div><div><Trophy size={15}/><strong>{score(progress)}<span> XP</span></strong><small>MISSION SCORE</small></div></div>
      <div className="progress-track"><span style={{ width: `${progress.solved.length / challenges.length * 100}%` }}/></div>
      <div className="objectives-heading"><span>OBJECTIVES</span><span>{progress.solved.length === 5 ? 'COMPLETE' : 'IN PROGRESS'}</span></div>
      <div className="missions">{challenges.map((c, i) => { const done = progress.solved.includes(c.id), unlocked = isUnlocked(c, progress.solved); return <button key={c.id} className={`mission ${done ? 'done' : ''} ${!unlocked ? 'locked' : ''} ${next?.id === c.id ? 'current' : ''}`} onClick={() => { if (!started) { setStarted(true); } if (done || error) interact(c.id); else if (!unlocked) interact(c.id); else { setDestination([c.position[0], c.position[1] + 2.6]); setToast(`Head to ${c.title}. Click the floor or use WASD, then press E nearby.`); } }}><span className="mission-number" style={{ color: unlocked ? c.color : undefined }}>{done ? <Check size={18}/> : unlocked ? `0${i + 1}` : <LockKeyhole size={15}/>}</span><span className="mission-copy"><small>{c.category}</small><strong>{c.title}</strong><span>{done ? 'Flag captured · Review debrief' : !unlocked ? `Requires ${c.requires.map(id => `0${challenges.findIndex(x => x.id === id) + 1}`).join(' + ')}` : `${c.points} XP · ${next?.id === c.id ? 'Ready to investigate' : 'Available'}`}</span></span>{unlocked && <ChevronRight size={15}/>}</button>; })}</div>
      <div className={`extraction ${progress.solved.length === 5 ? 'unlocked' : ''}`}><LockKeyhole size={17}/><div><strong>{progress.solved.length === 5 ? 'Extraction available' : 'Extraction locked'}</strong><p>{progress.solved.length === 5 ? 'Return to the south gate and press E.' : 'Capture all 5 flags to unlock the exit.'}</p></div>{error && progress.solved.length === 5 && <button onClick={() => interact('exit')}>Exit</button>}</div>
      <footer className="panel-footer"><span><Clock3 size={14}/> {duration(progress.seconds)}</span><span>{saved ? 'SAVED ON THIS DEVICE' : 'SAVE UNAVAILABLE'}</span><button className="icon-button" aria-label="Reset mission progress" onClick={() => setReset(true)}><RotateCcw size={15}/></button></footer>
    </aside></div>
    {toast && <div className="toast" role="status"><Crosshair size={17}/>{toast}</div>}
    {!started && !progress.extracted && <div className="overlay welcome-overlay"><section className="welcome modal" role="dialog" aria-modal="true" aria-labelledby="welcome-title"><div className="eyebrow"><span className="live-dot"/> FIELD BRIEFING / 001</div><h2 id="welcome-title">You’re inside.<br/><span>Now find the breach.</span></h2><p>A quiet facility. Five exposed systems. Investigate the evidence, recover each <code>CTF{'{flag}'}</code>, and unlock extraction.</p><div className="briefing-meta"><span><Terminal size={17}/> 5 hands-on labs</span><span><Clock3 size={17}/> 15–25 min</span><span><Shield size={17}/> Beginner friendly</span></div><button autoFocus className="primary" onClick={() => setStarted(true)}>{progress.solved.length || progress.seconds ? 'Resume operation' : 'Enter the facility'}<ArrowUpRight size={19}/></button><small>WASD to move · E to investigate · Hints available in every lab</small></section></div>}
    {error && started && !active && <div className="fallback"><strong>3D rendering is unavailable on this device.</strong><p>You can still complete every lab using the objective buttons.</p></div>}
    {active && <Lab key={active.id} challenge={active} progress={progress} capture={answer => capture(active, answer)} onClose={() => setActive(null)} hint={() => setProgress(p => ({ ...p, hints: { ...p.hints, [active.id]: Math.min(active.hints.length, (p.hints[active.id] || 0) + 1) } }))}/>}
    {help && <div className="overlay"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="help-title"><button className="close" aria-label="Close help" onClick={() => setHelp(false)}><X/></button><span className="eyebrow">FIELD MANUAL</span><h2 id="help-title">Learn by investigating.</h2><p>Move with WASD or arrow keys; hold Shift to run, and press Space to jump (or use the on-screen jump button). Click the floor to walk. Stand near a colored console and press E to open a lab.</p><p>Use <code>ls</code> to list evidence, <code>cat filename</code> to inspect it, and <code>help</code> to see commands. Recover the answer and submit the exact <code>CTF{'{...}'}</code> flag.</p><p>Each hint costs 15 XP. Captured flags unlock later labs. Finish all five and return to the extraction gate. Escape closes panels. Switch between overhead and third-person with the camera selector or V. In third-person, hold Q / R, hold the on-screen rotation buttons, or drag with the right mouse button to orbit. Movement follows the camera direction.</p><p className="subtle">The terminal operates entirely on fictional local evidence. Progress saves in this browser. The mission clock pauses here and when the tab is hidden.</p><button autoFocus className="primary" onClick={() => setHelp(false)}>Understood<Check size={18}/></button></section></div>}
    {reset && <div className="overlay"><section className="modal compact" role="alertdialog" aria-modal="true" aria-labelledby="reset-title"><h2 id="reset-title">Restart the operation?</h2><p>This clears this device’s flags, hints, score, and mission time.</p><div className="button-row"><button autoFocus className="secondary" onClick={() => setReset(false)}>Keep progress</button><button className="primary" onClick={() => { setProgress(freshProgress()); setReset(false); setStarted(false); setActive(null); setDestination([0, 8.8]); }}>Restart mission</button></div></section></div>}
    {progress.extracted && <div className="overlay"><section className="modal victory" role="dialog" aria-modal="true" aria-labelledby="victory-title"><div className="victory-icon"><Shield size={40}/></div><span className="eyebrow">OPERATION COMPLETE</span><h2 id="victory-title">Perimeter secured.</h2><p>Five flags captured. Five defenses learned.<br/>You found the breach and made it out.</p><div className="victory-stats"><span><strong>{score(progress)}</strong>MISSION XP</span><span><strong>{duration(progress.seconds)}</strong>ELAPSED TIME</span><span><strong>5/5</strong>FLAGS</span></div><button autoFocus className="primary" onClick={() => { setProgress(p => ({ ...p, extracted: false })); setStarted(true); }}>Explore & review debriefs<ArrowUpRight size={18}/></button><button className="text-button" onClick={() => { setProgress(freshProgress()); setStarted(false); setDestination([0, 8.8]); }}>Start a new operation</button></section></div>}
  </main>;
}

function Lab({ challenge: c, progress, capture, onClose, hint }: { challenge: Challenge; progress: Progress; capture: (s: string) => string; onClose: () => void; hint: () => void }) {
  const [lines, setLines] = useState<string[]>([`CIPHER OS / ${c.id.toUpperCase()}\nConnected to isolated training console.\nType help for commands or select an evidence file.`, runCommand(c, 'ls')]);
  const [command, setCommand] = useState(''); const [flag, setFlag] = useState(''); const [feedback, setFeedback] = useState(''); const [history, setHistory] = useState<string[]>([]); const historyIndex = useRef(0); const log = useRef<HTMLDivElement>(null);
  const done = progress.solved.includes(c.id); const hints = progress.hints[c.id] || 0;
  useEffect(() => { log.current?.scrollTo(0, log.current.scrollHeight); }, [lines]);
  const execute = (text: string) => { if (!text.trim()) return; setHistory(h => [...h, text]); historyIndex.current = history.length + 1; if (text.trim() === 'clear') setLines([]); else { const result = text.trim().startsWith('submit ') ? capture(text.trim().slice(7)) : runCommand(c, text); setLines(p => [...p.slice(-100), `trainee@${c.id}:~$ ${text}`, result]); } setCommand(''); };
  return <div className="overlay lab-overlay"><section className="lab modal" role="dialog" aria-modal="true" aria-labelledby="lab-title"><header className="lab-header"><div><span className="eyebrow" style={{ color: c.color }}>{c.category} / {c.points} XP</span><h2 id="lab-title">{c.title}</h2></div><button className="icon-button" aria-label="Close lab" onClick={onClose}><X size={23}/></button></header><div className="lab-content"><div className="lab-brief"><span className="eyebrow">YOUR OBJECTIVE</span><p>{c.briefing}</p><span className="eyebrow">EVIDENCE FILES</span><div className="files">{Object.keys(c.files).map(f => <button key={f} onClick={() => execute(`cat ${f}`)}><Terminal size={14}/>{f}<ChevronRight size={14}/></button>)}</div><div className="hints">{c.hints.slice(0, hints).map((h, i) => <p key={h}><strong>HINT {i + 1}</strong>{h}</p>)}<button className="secondary" disabled={hints === c.hints.length || done} onClick={hint}><HelpCircle size={15}/>{hints === c.hints.length ? 'All hints revealed' : 'Reveal hint · −15 XP'}</button></div></div><div className="terminal-pane"><div className="terminal-top"><span><i/><i/><i/></span>trainee@{c.id} <span>SIMULATED SHELL</span></div><div className="terminal-log" ref={log} role="log" aria-live="polite">{lines.map((line, i) => <pre key={i} className={line.startsWith('trainee@') ? 'command-line' : ''}>{line}</pre>)}</div><form className="terminal-input" onSubmit={e => { e.preventDefault(); execute(command); }}><span>❯</span><input autoFocus aria-label="Terminal command" value={command} onChange={e => setCommand(e.target.value)} spellCheck={false} autoComplete="off" placeholder="Type help to begin…" onKeyDown={e => { if (e.key === 'ArrowUp') { e.preventDefault(); historyIndex.current = Math.max(0, historyIndex.current - 1); setCommand(history[historyIndex.current] || ''); } if (e.key === 'ArrowDown') { e.preventDefault(); historyIndex.current = Math.min(history.length, historyIndex.current + 1); setCommand(history[historyIndex.current] || ''); } }}/><button type="submit" aria-label="Run command"><ChevronRight size={18}/></button></form></div></div>{done ? <div className="debrief"><span><Check size={20}/> FLAG CAPTURED</span><p>{c.lesson}</p><button className="primary" onClick={onClose}>Return to facility<ArrowUpRight size={17}/></button></div> : <form className="flag-form" onSubmit={e => { e.preventDefault(); setFeedback(capture(flag)); }}><label htmlFor="flag">CAPTURE THE FLAG</label><div><input id="flag" value={flag} onChange={e => setFlag(e.target.value)} placeholder="CTF{your_answer}" autoComplete="off" spellCheck={false}/><button className="primary" type="submit">Submit flag<Flag size={16}/></button></div>{feedback && <p role="status">{feedback}</p>}</form>}</section></div>;
}





